language: scala

# This is only necessary for trying out oraclejdk9, which doesn't yet work on their side
# sudo: false
# dist: trusty

jdk:
  - oraclejdk8

script:
  - sbt ++2.13.0-M4 compile

after_success:
  - bash <(curl -s https://codecov.io/bash)
